# Trabajo Practico FINAL
Participantes:
Alexis Aramis Torchinsky

In [1]:
### 1) Construya 2 datasets, uno con los datos originales y otro con los datos escalados y/o normalizados. 
### Divida ambos datasets en conjuntos de entrenamiento y de validación.
#Imports
import numpy as np
import pandas as pd
import sklearn.model_selection
from sklearn import preprocessing
from sklearn.datasets import load_wine

# carga del dataload orginal de Wine recognition dataset
wine=load_wine()
etiquetas=wine.target
#print(etiquetas)
originalData = pd.DataFrame(wine.data)
#print("Original Wine Data")
#print(originalData)
#Conjuntos de Entrenamiento y Validacion de Datos Originales
OrigD_X_train, OrigD_X_test, OrigD_y_train, OrigD_y_test=sklearn.model_selection.train_test_split(
        originalData,
        range(len(originalData)),
        test_size=0.2,
        shuffle=True)
TagOrigD_y_train=etiquetas[OrigD_y_train]
TagOrigD_y_test=etiquetas[OrigD_y_test]
#print(TagOrigD_y_train)
#print(TagOrigD_y_test)
#Conjuntos de Entrenamiento y Validacion de Datos Normalizados
normalizedData=preprocessing.normalize(originalData,norm='l1',axis=0)
#print("Normalized Wine data")
#print(normalizedData)
NormD_X_train, NormD_X_test, NormD_y_train, NormD_y_test=sklearn.model_selection.train_test_split(
        normalizedData,
        range(len(originalData)),
        test_size=0.2,
        shuffle=True)
TagNormD_y_train=etiquetas[NormD_y_train]
TagNormD_y_test=etiquetas[NormD_y_test]
#print(TagNormD_y_train)
#print(TagNormD_y_test)

# Analisis por metodo KNN
Elija un valor de K y aplique el algoritmo de KNN en ambos datasets. 

Evalúe la precisión en ambos casos sobre el conjunto de validación correspondiente. 

Analice brevemente los resultados obtenidos

In [2]:
#Imports
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn import neighbors, datasets
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

### Setup de KNN
sc_X=StandardScaler()
#OrigD_X_train=sc_X.fit_transform(OrigD_X_train)
#OrigD_X_test=sc_X.fit_transform(OrigD_X_test)
import math
n_neighbors = int(math.sqrt(len(OrigD_y_test))) #15
#n_neighbors=15
print(f"neighbors calculados como Raiz de la longitud del dataset: {n_neighbors}")
### Aplicamos el modelo KNN para el DS Original de training
print("=========================================================")
print("-------- Analisis por KNN sobre datos originales --------")
for weights in ['uniform', 'distance']:
    # Creamos una instancia del clasificador de vecinos más cercanos y le pasamos los datos mediante fit().
    # base sobre dataset Original de TRainig(OTR)
    classifierOTR = neighbors.KNeighborsClassifier(n_neighbors, weights=weights, metric='euclidean')
    classifierOTR.fit(OrigD_X_train, TagOrigD_y_train)
    
    predictOTR = classifierOTR.predict(OrigD_X_test)
    print(f"Prediccion por {weights}")
    print(TagOrigD_y_test)
    print(predictOTR)
    print(f"Presicion: {accuracy_score(TagOrigD_y_test, predictOTR)}")
print("=========================================================")


### Aplicamos el modelo KNN para el DS Normalizados de training
print("=========================================================")
print("-------- Analisis por KNN sobre datos NORMALIZADOS --------")
for weights in ['uniform', 'distance']:
    # Creamos una instancia del clasificador de vecinos más cercanos y le pasamos los datos mediante fit().
    # base sobre dataset Normalizado de TRainig(NTR)
    classifierNTR = neighbors.KNeighborsClassifier(n_neighbors, weights=weights, metric='euclidean')
    classifierNTR.fit(NormD_X_train, TagNormD_y_train)
    
    predictNTR = classifierNTR.predict(NormD_X_test)
    print(f"Prediccion por {weights}")
    print(TagNormD_y_test)
    print(predictNTR)
    print(f"Presicion: {accuracy_score(TagNormD_y_test, predictNTR)}")
print("=========================================================")


neighbors calculados como Raiz de la longitud del dataset: 6
-------- Analisis por KNN sobre datos originales --------
Prediccion por uniform
[1 0 0 0 2 2 0 2 1 1 1 0 2 2 2 1 0 1 0 1 0 1 2 0 1 0 0 0 0 2 0 0 1 2 1 0]
[1 0 0 0 1 2 0 2 1 2 1 0 2 2 2 2 0 1 2 1 2 1 2 0 2 1 0 2 2 2 2 0 2 2 1 0]
Presicion: 0.6944444444444444
Prediccion por distance
[1 0 0 0 2 2 0 2 1 1 1 0 2 2 2 1 0 1 0 1 0 1 2 0 1 0 0 0 0 2 0 0 1 2 1 0]
[1 0 0 0 1 2 0 2 1 2 1 0 2 2 2 2 0 1 1 1 1 1 2 0 2 0 0 2 2 2 2 0 2 2 1 0]
Presicion: 0.7222222222222222
-------- Analisis por KNN sobre datos NORMALIZADOS --------
Prediccion por uniform
[2 1 0 1 0 2 0 1 0 0 1 0 0 2 1 2 1 1 0 2 1 1 2 1 2 1 1 2 1 1 2 0 0 0 0 0]
[2 1 0 1 0 2 0 1 0 0 1 0 0 2 1 2 0 1 0 2 1 1 2 1 2 1 1 2 0 1 2 0 0 0 0 0]
Presicion: 0.9444444444444444
Prediccion por distance
[2 1 0 1 0 2 0 1 0 0 1 0 0 2 1 2 1 1 0 2 1 1 2 1 2 1 1 2 1 1 2 0 0 0 0 0]
[2 1 0 1 0 2 0 1 0 0 1 0 0 2 1 2 1 1 0 2 1 1 2 1 2 1 1 2 1 1 2 0 0 0 0 0]
Presicion: 1.0


## KNN: Breve analisis de los resultados
Luego de varias ejecuciones depurando el kernel todas las presiciones obtenidas con los datos normalizados se encuentran por encima del 94%, mientras que los modelos entrenados sobre los datos originales sin preprosesar nunca super el 75% de la presicion.

Asi mismo, en ambos entrenamientos(datos originales y datos normalizados) se ve una mejora consistente de la presicion(3 puntos para datos normalizados, 6 a 9 puntos porcentuales para datos originales) cuando se utiliza el pesaje con el metodo de "inversa de la distancia" versus el uniforme.


# Analisis por Arboles de desicion

Elija un valor de max_depth y aplique el algoritmo de Árboles de Decisión en ambos datasets. 

Evalúe la precisión en ambos casos. sobre el conjunto de validación correspondiente. Analice brevemente los resultados obtenidos

In [6]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
import graphviz
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

arbolOTR=DecisionTreeClassifier(max_depth=5)
arbolOTR.fit(OrigD_X_train, TagOrigD_y_train)

print(f"Score del Arbol sobre datos Originales de entrenamiento: {arbolOTR.score(OrigD_X_train, TagOrigD_y_train)}")

print(f"Score del Arbol sobre datos Originales de test: {arbolOTR.score(OrigD_X_test, TagOrigD_y_test)}")

#export_graphviz(
#    arbolOTR, 
#    out_file='arbol1.dot', 
#    class_names=wine.target_names, 
#    feature_names=wine.feature_names, 
#    impurity=False, 
#    filled=True)

#with open('arbol1.dot') as f:
#    dot_graph=f.read()

#graphviz.Source(dot_graph)

#from sklearn.tree import plot_tree
#plot_tree(arbolOTR)

Score del Arbol sobre datos Originales de entrenamiento: 1.0
Score del Arbol sobre datos Originales de test: 0.9444444444444444


In [7]:
arbolNTR=DecisionTreeClassifier(max_depth=5)
arbolNTR.fit(NormD_X_train, TagNormD_y_train)

print(f"Score del Arbol sobre datos Normalizados de entrenamiento: {arbolNTR.score(NormD_X_train, TagNormD_y_train)}")

print(f"Score del Arbol sobre datos Normalizados de test: {arbolNTR.score(NormD_X_test, TagNormD_y_test)}")


Score del Arbol sobre datos Normalizados de entrenamiento: 1.0
Score del Arbol sobre datos Normalizados de test: 0.9444444444444444


## Arboles de Desicion: Breve analisis de los resultados
Luego de varias ejecuciones depurando el kernel todas las presiciones obtenidas para el dataset de validacion tanto con los datos originales como los normalizados se mantienen en un 94,4%. El mismo nivel de presicion se da tanto para una profundidad de 3 y de 5 niveles. Con lo que se podria concluir que es analisis por arboles de desicion para este modelo es sumamente consistente.
Tambien ya se visualiza que para este dataset el modelo KNN obtiene mejor score que los Arboles aunque menos consistente.


# Analisis por PCA

Aplique el algoritmo PCA a los datos escalados y/o normalizados para reducir su dimensionalidad a 2, y grafique el conjunto resultante.

In [9]:
install mglearn
import mglearn


SyntaxError: invalid syntax (3331713977.py, line 1)