# Trabajo Practico FINAL
Participantes:
Alexis Aramis Torchinsky

In [4]:
### 1) Construya 2 datasets, uno con los datos originales y otro con los datos escalados y/o normalizados. 
### Divida ambos datasets en conjuntos de entrenamiento y de validación.
#Imports
import numpy as np
import pandas as pd
import sklearn.model_selection
from sklearn import preprocessing
from sklearn.datasets import load_wine

# carga del dataload orginal de Wine recognition dataset
wine=load_wine()
etiquetas=wine.target
#print(etiquetas)
originalData = pd.DataFrame(wine.data)
#print("Original Wine Data")
#print(originalData)
#Conjuntos de Entrenamiento y Validacion de Datos Originales
OrigD_X_train, OrigD_X_test, OrigD_y_train, OrigD_y_test=sklearn.model_selection.train_test_split(
        originalData,
        range(len(originalData)),
        test_size=0.2,
        shuffle=True)
TagOrigD_y_train=etiquetas[OrigD_y_train]
TagOrigD_y_test=etiquetas[OrigD_y_test]
#print(TagOrigD_y_train)
#print(TagOrigD_y_test)
#Conjuntos de Entrenamiento y Validacion de Datos Normalizados
normalizedData=preprocessing.normalize(originalData,norm='l1',axis=0)
#print("Normalized Wine data")
#print(normalizedData)
NormD_X_train, NormD_X_test, NormD_y_train, NormD_y_test=sklearn.model_selection.train_test_split(
        normalizedData,
        range(len(originalData)),
        test_size=0.2,
        shuffle=True)
TagNormD_y_train=etiquetas[NormD_y_train]
TagNormD_y_test=etiquetas[NormD_y_test]
#print(TagNormD_y_train)
#print(TagNormD_y_test)

# Analisis por metodo KNN
Elija un valor de K y aplique el algoritmo de KNN en ambos datasets. 

Evalúe la precisión en ambos casos sobre el conjunto de validación correspondiente. 

Analice brevemente los resultados obtenidos

In [5]:
#Imports
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn import neighbors, datasets
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

### Setup de KNN
sc_X=StandardScaler()
#OrigD_X_train=sc_X.fit_transform(OrigD_X_train)
#OrigD_X_test=sc_X.fit_transform(OrigD_X_test)
import math
n_neighbors = int(math.sqrt(len(OrigD_y_test))) #15
#n_neighbors=15
print(f"neighbors calculados como Raiz de la longitud del dataset: {n_neighbors}")
### Aplicamos el modelo KNN para el DS Original de training
print("=========================================================")
print("-------- Analisis por KNN sobre datos originales --------")
for weights in ['uniform', 'distance']:
    # Creamos una instancia del clasificador de vecinos más cercanos y le pasamos los datos mediante fit().
    # base sobre dataset Original de TRainig(OTR)
    classifierOTR = neighbors.KNeighborsClassifier(n_neighbors, weights=weights, metric='euclidean')
    classifierOTR.fit(OrigD_X_train, TagOrigD_y_train)
    
    predictOTR = classifierOTR.predict(OrigD_X_test)
    print(f"Prediccion por {weights}")
    print(TagOrigD_y_test)
    print(predictOTR)
    print(f"Presicion: {accuracy_score(TagOrigD_y_test, predictOTR)}")
print("=========================================================")


### Aplicamos el modelo KNN para el DS Normalizados de training
print("=========================================================")
print("-------- Analisis por KNN sobre datos NORMALIZADOS --------")
for weights in ['uniform', 'distance']:
    # Creamos una instancia del clasificador de vecinos más cercanos y le pasamos los datos mediante fit().
    # base sobre dataset Normalizado de TRainig(NTR)
    classifierNTR = neighbors.KNeighborsClassifier(n_neighbors, weights=weights, metric='euclidean')
    classifierNTR.fit(NormD_X_train, TagNormD_y_train)
    
    predictNTR = classifierNTR.predict(NormD_X_test)
    print(f"Prediccion por {weights}")
    print(TagNormD_y_test)
    print(predictNTR)
    print(f"Presicion: {accuracy_score(TagNormD_y_test, predictNTR)}")
print("=========================================================")


neighbors calculados como Raiz de la longitud del dataset: 6
-------- Analisis por KNN sobre datos originales --------
Prediccion por uniform
[0 0 2 0 1 0 2 1 2 1 0 1 0 0 0 2 1 1 1 0 1 0 1 2 0 1 0 1 1 0 2 2 2 0 1 0]
[0 0 2 0 2 0 2 1 1 1 0 0 0 0 0 1 1 2 1 0 1 0 1 2 0 1 0 1 1 2 1 2 2 0 1 0]
Presicion: 0.8055555555555556
Prediccion por distance
[0 0 2 0 1 0 2 1 2 1 0 1 0 0 0 2 1 1 1 0 1 0 1 2 0 1 0 1 1 0 2 2 2 0 1 0]
[2 0 2 0 2 0 2 1 2 1 0 0 0 0 0 1 1 2 1 0 1 1 1 2 0 1 0 2 2 2 2 2 2 1 1 0]
Presicion: 0.7222222222222222
-------- Analisis por KNN sobre datos NORMALIZADOS --------
Prediccion por uniform
[1 0 1 0 1 0 2 0 0 0 0 1 0 0 1 0 1 2 0 2 2 0 2 2 0 2 1 0 0 2 1 2 0 1 0 1]
[1 0 1 0 1 0 2 0 0 0 0 1 0 0 1 0 1 2 0 2 2 0 2 2 0 2 1 0 0 2 1 2 0 1 0 1]
Presicion: 1.0
Prediccion por distance
[1 0 1 0 1 0 2 0 0 0 0 1 0 0 1 0 1 2 0 2 2 0 2 2 0 2 1 0 0 2 1 2 0 1 0 1]
[1 0 1 0 1 0 2 0 0 0 0 1 0 0 1 0 1 2 0 2 2 0 2 2 0 2 1 0 0 2 1 2 0 1 0 1]
Presicion: 1.0


# Breve analisis de los resultados
Luego de varias ejecuciones depurando el kernel todas las presiciones obtenidas con los datos normalizados se encuentran por encima del 97%, mientras que los modelos entrenados sobre los datos originales sin preprosesar nunca super el 75% de la presicion.

Asi mismo, en ambos entrenamientos(datos originales y datos normalizados) se ve una mejora consistente de la presicion(3 puntos para datos normalizados, 6 a 9 puntos porcentuales para datos originales) cuando se utiliza el pesaje con el metodo de "inversa de la distancia" versus el uniforme.


# Analisis por Arboles de desicion

Elija un valor de max_depth y aplique el algoritmo de Árboles de Decisión en ambos datasets. 

Evalúe la precisión en ambos casos. sobre el conjunto de validación correspondiente. Analice brevemente los resultados obtenidos

In [6]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
import graphviz
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

arbolOTR=DecisionTreeClassifier(max_depth=3)
arbolOTR.fit(OrigD_X_train, TagOrigD_y_train)

print(f"Score del Arbol sobre datos de entrenamiento: {arbolOTR.score(OrigD_X_train, TagOrigD_y_train)}")

print(f"Score del Arbol sobre datos de test: {arbolOTR.score(OrigD_X_test, TagOrigD_y_test)}")

export_graphviz(
    arbolOTR, 
    out_file='arbol1.dot', 
    class_names=wine.target_names, 
    feature_names=wine.feature_names, 
    impurity=False, 
    filled=True)

with open('arbol1.dot') as f:
    dot_graph=f.read()

graphviz.Source(dot_graph)

from sklearn.tree import plot_tree
plot_tree(arbol)

ModuleNotFoundError: No module named 'graphviz'